name: Build  AWS S3

on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: string
jobs:
  # Build Job
  build:
    runs-on: ubuntu-20.04
    steps:
    - run: echo "Variable github user => ${{ vars.GITHUBUSER }}"
    - name: Checkout tools repo
      uses: actions/checkout@v4
      with:
        repository: ${{ vars.GITHUBUSER }}/devops-templates
        path: ./devops-templates
    
    - name: Build
      id: build
      uses: ./devops-templates/.github/actions/build

    - name: Upload artifact to enable deployment
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: ./dist
      
